### PR TITLE
wip: real pager with incremental search

### LINKED ISSUE #51: /-to-search in tui pager mode
should probably make an abstraction for jumping around the pager…

seems like a lot of work

### PR DESCRIPTION
**Pull request by amonks**
Closes #51

bubbles.Viewport isn't really appropriate for a buffer that we keep appending to like this: we have to manually bookkeep a lot of state back and forth between the tui and the viewports.

Instead, let's encapsulate the viewports and the log content together into a new ui component per-stream.

- adds vim-style incremental search with highlighting
- scroll performance is now roughly O(window height) instead of O(buffer size)
- adds "responsive design", making the ui a lot smaller in small windows
- moves tui help into its own pane, accessed with 'h' or '?'
- adds a bonus package, cmd/scroll, which is a tail replacement of dubious value
- now requires go 1.22

### CODE REVIEW

**Comment by amonks** [comment]
@cgsdev0 @ecshreve

sarah and eric — i took a stab at some ui changes; pls try this branch and lmk what you think; very happy to make changes if any of this doesn't feel right to y'all

**Comment by ecshreve** [comment]
Pulled the branch and swapped it in for `run` in a project I had open and it works great!

Some quick opinions and one possible bug
- I like having the the short help menu up all the time because I'm very forgetful, not possible now
- Pressing ? or h brings up the help pane over everything else which feel kinda weird to go from full screen colorful output to a single column black and white all the way on the left
- I don't know why I feel this way, but when I was in the help pane I kept trying to hit 'h' of '?' again the close it. don't feel too strongly on that but it came to mind
- Possibly due to me needing a new glasses prescription, but I kinda miss having a box around the logs as a separator from the task list, now theres a whole lot of color on the left of my terminal and the last list feels like it's bleeding into the interleaved output almost

🐛 ❓  Could have been intentional, but now I can only scroll the log pane if it's focused, normally I can scroll up and down while the task list is still focused.

**Comment by amonks** [comment]
@ecshreve woot, thank you! this is exactly the kind of feedback I was looking for.

I bet we use run with different window sizes: lately I've been using run in a pane about 1/6 of my laptop screen (ie: small) so the help area was feeling like a waste of precious space—a big intent of this PR is making that size work better. It sounds like you mostly use a large window, where giving up log space for  ui affordances is a good tradeoff. 

helpfully, this branch adds some "responsive design" tooling, so I think we can make small windows work better without sacrificing usability on large windows. I'll play with putting the help shortcuts and full borders back in when the window is large. Would you send a screenshot of your typical run window size?

- "h" or "?" to close help is a great idea; will fix.
- styling the help better on large screens is a good idea also; will do

**Comment by ecshreve** [comment]
That makes sense a lot of sense, I do terminal things in two main scenarios,

1. in VSCode intergrated terminal in a small section about the size you mentioned,  i have it set with the terminal along the bottom split into two panes, with run living in one of them sized so the output was readable
2. I have alacritty running in a fullscreen window all the time where ill do more terminal-centric things

When i was spinning up your branch i did in my fullscreen window first, where it did look a bit wonky. Then I tried it again in VSCode and it definitely looked more natural in the smaller pane.

**Comment by ecshreve** [comment]
After looking and thinking for a minute, I take back what I said about big windows, a majority of the time i have it down in a small window in vscode fwiw

---

What it looks like OLD:

Screenshot 2024-03-30 at 10 19 36 AM
Screenshot 2024-03-30 at 10 17 21 AM

What it looks like NOW with these updates:
Screenshot 2024-03-30 at 10 19 36 AM
Screenshot 2024-03-30 at 10 23 05 AM

**Comment by ecshreve** [comment]
Okay revising my feedback after spending more time with the updates.
- I don't care about the border box at all anymore, the new layout is nice and clean and works well without a box
  - Maybe we add a feature where "L" cycles through a handful of layout options and one of them includes a bordered box. 🤔 

- I still miss the help text, maybe we can pop into a viewport under the task when "h" or "?"
Screenshot 2024-03-30 at 10 38 06 AM

**Comment by amonks** [comment]
thanks!

based on your feedbackI think I still want to play with two changes here (in addition to the bugfixes):
- include some subset of the help text on sufficiently large screens. I still feel pretty hardline about not including it on _very_ small screens, but maybe the threshold is low. Maybe the vscode panel is large enough that we can comfortably fit some shortcuts. I'm open to a second toggle for inline help, but I'd prefer not to have one if we don't need it. let's try to find a good toggle-free experience first. I think as we add features, we will -eventually- need a togglable full-page help, even if we don't need one today, so I feel more comfortable with that than I do with maintaining toggleable inline help.
- use some more negative space on very large screens — I think the new UI is strictly better in the small-vscode-panel context, but maybe not quite as good as the old UI in a very large screen context. I don't know whether the border boxes are the right way to make the menu and logs visually distinct, but I agree with you that, if we have enough room, it is good to spend some more of that room to make them more distinct. I played around with using background color for this but I didn't love it.

**Comment by amonks** [comment]
@ecshreve —
I took a pass at adding inline help on tall screens
I'm not especially confident that the breakpoints feel right here (or anywhere tbh), but I think the help display is ok
wdyt?

(I haven't yet looked at making the log and menu more visually distinct)

**Comment by amonks** [comment]
convenience screenshot, altho this will def look different on your machine:
Screenshot 2024-03-30 at 7 10 55 PM

**Comment by amonks** [comment]
I'm pretty happy with where this ended up. I'm gonna keep running this overnight (to confirm that it fixes my issue where run grinds to a halt after running for a while) and then probably cut a new release tomorrow.

@cgsdev0 iirc you have folks using run IRL. Just to help calibrate my level of attention around the release process: are releases potentially disruptive for y'all or do you have a version pinned?

**Comment by cgsdev0** [comment]
> are releases potentially disruptive for y'all or do you have a version pinned?

nah you're good we are pinned

**Comment by cgsdev0** [comment]
the search is very nice

some suggestions from me:
* i prefer scrolling through logs by pages; support for pageup / ctrl+u and pagedown / ctrl+d would be greatly appreciated
* now that esc/q have multiple uses, i kinda wish they just didnt exit the program. it's easy to double press the key unintentionally
* ctrl+c doesnt immediately close the program anymore
* would be nice to have some way to easily clear the search
* would be nice to have a cursor for the search when it's focused
* maybe prevent scrolling if the window isnt full? its weird that scrolling takes you out of the 'tail' mode (permanently?)
* `H` being help felt a little weird; i kinda wish `H` and `L` were "select task" and "deselect task"
* the responsive thing is cool

> Maybe we add a feature where "L" cycles through a handful of layout options and one of them includes a bordered box. 🤔

in a previous project i implemented something like this; particularly it would toggle between having the task list as a sidebar vs. having it above the pager

**Comment by amonks** [comment]
@cgsdev0 

I agree with basically all of these suggestions!

> maybe prevent scrolling if the window isnt full? its weird that scrolling takes you out of the 'tail' mode (permanently?)

is particularly interesting. Re the `?`, G puts you back into tail mode, but the fact you asked shows this isn’t clear. 

I feel mixed about making it harder to quit. In another project, I supported all of {q,esc,ctrl+c}, but showed a “press $char again to quit” confirmation in the status bar on first press. I think that would be good here too.

**Comment by amonks** [comment]
OK, this time it's real.

I think I've addressed all y'all's suggestions, except:

- @ecshreve: I tried in #103 to give more emphasis to the selected pane using background colors, but ended up walking that back. Partly for technical reasons, and partly because @cgsdev0 suggested it would be polite to respect peoples' color themes. I think there's still room to emphasize the selected panel more, particularly on large screens, but I'd like to merge this and think about that later.
- @cgsdev0: I'm not preventing scrolling if the window is not full — it felt kind of weird to me in practice. I did change the helptext for end/G to include the word "tail", which is, at least, a gesture towards clarity.

I'm going to merge this now and cut a build.

**Comment by ecshreve** [comment]
This is a great change, I'm digging the new version.  🎉

**Pull request merged**
