### PR TITLE
ecs - examples - go app  with taskfile example

### PR DESCRIPTION
**Pull request by ecshreve**
This example is adapted from a taskfile I use personally for new projects, and I thought it could be useful!

Changes

- Added a commit with a new version of the README I played around with, not sure it fits in this PR but I was working on it in tandem with the golang app example.
- Create Golang App example in a new `examples` directory (see `examples/golang-app/README.md` for details)
- Rename existing `example` to `demo` and move into the `examples` directory
- Update screenshot tasks for generating gifs with new file paths
- Update references in README to new file paths
 
Questions
- what should the image paths be for the gifs in the readme? relative or absolute?
- how best to combine this with the existing example directory?
  - tried consolidating to single examples/ dir 
- should the `screenshot-golang` task live somewhere else?
  - yeah i think it should be in the root readme
  - screenshot dirs should probably be consolidated  
- when i run `run generate-docs` it fails on something related to `grep` and `sd` in that task

### CODE REVIEW

**Review by amonks — COMMENTED** [review]
I love the idea of having more realistic example code!

I also love application bootstrapping/management scripts — I think "rails-like" experiences are super valuable and super under-explored — work in this space is awesome.

but that isn't what most go projects look like, so I don't think it makes for a very communicative example of a run integration, as opposed to, like, an http server. i think a good quality for example code is that each part either 1. shows something specific about run, or, 2. is so familiar to the median go developer that it obviously does _not_ show something about run.

***

do you still have the dev branch w unsquashed readme changes? I'd love to see that as a separate pr if it's convenient

**Comment by ecshreve** [comment]
Sweet! That all sounds great to me and makes sense. I had a ton of fun writing it, very much like this tool. 

 And yep! Here's the branch with the readme changes broken out: https://github.com/amonks/run/pull/92 
 Just need to pop one commit off that branch that's unrelated  real quick

**Comment by ecshreve** [comment]
Okay, these two PRs are broken apart now  🪨 🔨

**Comment by amonks** [comment]
thanks! I'll look at the readme stuff next.

I'm gonna close this, but I'd totally welcome,
- an issue for talking about rails-like app scaffolding/generators — I don't think this necessarily fits into "run", but it's def a project I'm interested in.
- a PR making the example more realistic without introducing new concepts; I opened #93 to track this. (you're welcome to do this but I'm not voluntelling you: I'll get to it soonish if you don't feel like it)

**Pull request closed without merging**
